# Generated by Django 5.2.1 on 2025-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL-слаг'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
