# Generated by Django 5.2.1 on 2025-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_slug_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-слаг'),
        ),
    ]
