# Generated by Django 5.1.1 on 2025-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
