# Generated by Django 5.1.1 on 2025-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_news_of_the_day',
            field=models.BooleanField(default=False, verbose_name='Новость дня'),
        ),
    ]
