# Generated by Django 5.2.1 on 2025-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_is_news_of_the_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('copyright_text', models.CharField(max_length=200, verbose_name='Текст копирайта')),
                ('registration_info', models.CharField(max_length=200, verbose_name='Информация о регистрации')),
                ('editor_info', models.CharField(max_length=200, verbose_name='Информация о редакторе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Содержимое футера',
                'verbose_name_plural': 'Содержимое футера',
            },
        ),
    ]
