# Generated by Django 5.2.1 on 2025-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_footercontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercontent',
            name='editor_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Информация о редакторе'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='registration_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Информация о регистрации'),
        ),
    ]
