# Generated by Django 5.2.1 on 2025-06-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_footercontent_editor_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные поля'),
        ),
    ]
