# Generated by Django 5.2.1 on 2025-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_footercontent_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='copyright_text_font_size',
            field=models.CharField(default='0.9rem', help_text='Например: 14px, 0.9em, 0.8rem', max_length=20, verbose_name='Размер шрифта Текста копирайта'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='editor_info_font_size',
            field=models.CharField(blank=True, default='0.9rem', help_text='Например: 14px, 0.9em, 0.8rem', max_length=20, verbose_name='Размер шрифта Информации о редакторе'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='registration_info_font_size',
            field=models.CharField(blank=True, default='0.9rem', help_text='Например: 14px, 0.9em, 0.8rem', max_length=20, verbose_name='Размер шрифта Информации о регистрации'),
        ),
        migrations.AddField(
            model_name='footercontent',
            name='site_name_font_size',
            field=models.CharField(default='1.2rem', help_text='Например: 16px, 1.2em, 1.5rem', max_length=20, verbose_name='Размер шрифта Названия сайта'),
        ),
        migrations.AlterField(
            model_name='footercontent',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные поля (текст и размер шрифта)'),
        ),
    ]
