# Generated by Django 5.2.3 on 2025-06-13 11:22

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_footercontent_copyright_text_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.news_image_path, verbose_name='Изображение'),
        ),
    ]
